// Mocks generated by Mockito 5.4.2 from annotations
// in motopay_assessment_test/test/app/data/use_cases/use_cases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:motopay_assessment_test/src/app/data/models/punk.dart' as _i5;
import 'package:motopay_assessment_test/src/app/domain/repositories/repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Repository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepository extends _i1.Mock implements _i3.Repository {
  MockRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<String, List<_i5.Punk>>> getPunks({
    int? page,
    int? perPage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPunks,
          [],
          {
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue: _i4.Future<_i2.Either<String, List<_i5.Punk>>>.value(
            _FakeEither_0<String, List<_i5.Punk>>(
          this,
          Invocation.method(
            #getPunks,
            [],
            {
              #page: page,
              #perPage: perPage,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<String, List<_i5.Punk>>>);
}
